apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: ecomerce
        - name: POSTGRES_USER
          value: ecomerce
        - name: POSTGRES_PASSWORD
          value: Pg1234
---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
    spec:
      containers:
      - name: fakeshop
        image: jaxstar/fake-shop-desafio:v2
        ports:
        - containerPort: 5000
        env:
        - name: DB_NAME
          value: ecomerce
        - name: DB_USER
          value: ecomerce
        - name: DB_PASSWORD
          value: Pg1234
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: FLASK_APP
          value: index.py
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: fastshop
# spec:
#   selector:
#     app: fakeshop
#   ports:
#     - protocol: TCP
#       port: 5000
#       targetPort: 5000
#       nodePort: 30000
#   type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fastshop
spec:
  selector:
    app: fakeshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer