name: FakeShop
run-name: "FakeShop ${{ github.run_number }}"

on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
 CI:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4


 CD:
  runs-on: ubuntu-latest
  needs: [CI]
  steps:
  - run: "echo CD"
  

