name: FakeShop
run-name: "FakeShop ${{ github.run_number }}"

on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
 CI:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  
  - run: |
      ls -lha
      pwd
      cd ..
      echo "========================"
      ls -lha
      echo "========================"
      pwd
    name: "Primeiro"

 CD:
  runs-on: ubuntu-latest
  steps:
  - run: "echo CD"
  

