name: FakeShop
run-name: "FakeShop ${{ github.run_number }}"

on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
 CI:
  runs-on: ubuntu-latest
  environment: dev
  steps:
  - run: echo  "${{ github.workspace}}"
  - uses: actions/checkout@v4
  - uses: docker/login-action@v3
    with:
      username: ${{ vars.DOCKERHUB_USERNAME  }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  - name: Build and push
    uses: docker/build-push-action@v6
    with:
      push: true
      context: ${{ github.workspace}}/src
      tags: |
        ${{ vars.DOCKERHUB_USERNAME  }}/${{ vars.DOCKER_IMAGE}}:v${{ github.run_number }}
        ${{ vars.DOCKERHUB_USERNAME  }}/${{ vars.DOCKER_IMAGE}}

 CD:
  runs-on: ubuntu-latest
  needs: [CI]
  environment: dev
  steps:
  - uses: azure/k8s-set-context@v4
    with:
       method: kubeconfig
       kubeconfig: ${{ secrets.KUBERNETES_CONFIG }}
  

